# Generated by Django 5.0.1 on 2024-01-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "species",
                    models.CharField(
                        choices=[("Cat", "cat"), ("Dog", "dog")], max_length=16
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
    ]
